---
abstract: 'PSGI handler for FCGI::EV'
author:
  - mala
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Handler::FCGI::EV
name: Plack-Handler-FCGI-EV
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 5.3
  EV: 4
  FCGI::EV: 1.0.7
  Plack: 0.9977
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Handler-FCGI-EV.git
version: 0.01
